"""
Note: this rater utlizes gpt-3.5, so it cannot take files as input. Therefore, only the text but not the format is considered.
"""


import requests
import json
import datetime
import os
from dotenv import load_dotenv

load_dotenv()

url = os.getenv('url')
auth_key = os.getenv("auth_key")

def get_advice(theme: str, content: str) -> str:
	payload = json.dumps({
	   "model": "gpt-3.5-turbo",
	   "messages": [
	      {
	         "role": "system",
	         "content": "You are a resume writing tutor. Your job is to pretend that you are a professional human resource manager who hires new employees. You need to read the resume and then provide a rating (at the scale of 0-100) and some feedback on how to improve the resume. You can also provide feedback on having the user remove unrelated experience and/or includes most recent activities. The user is writing a resume for " + str(theme) + "Current date: " + str(datetime.date.today())
	      },
	      {
	         "role": "user",
	         "content": content
	      }
	   ]
	})
	headers = {
	   'Authorization': 'Bearer ' + auth_key,
	   'User-Agent': 'Apifox/1.0.0 (https://apifox.com)',
	   'Content-Type': 'application/json'
	}
	
	response = json.loads(requests.request("POST", url, headers=headers, data=payload).text)
	
	#print(response)
	reply_text = response["choices"][0]["message"]["content"]
	
	return reply_text
	

if __name__ == '__main__':
	theme = "" # please briefly describe what the resume is for. E.g., a research assistant position in Computer Science, a part-time in restaurant
	content = "" #"My research experience at the Attention, Perception, & EXperience (APEX) Lab at the University of Chicago was significant in my journey in Computational Neuroscience. In the lab, I explored on the development of methods that integrate Compositional Pattern Producing Networks (CPPN) with the NeuroEvolution of Augmenting Topologies (NEAT) algorithm. This integration aimed to alter the evolutionary behavior of images generated by the program, which was both a technical challenge and a creative endeavor. It was fascinating to see how a set of simple evolutionary rules could lead to the emergence of complex and beautiful patterns, similar to the processes observed in natural evolution. This intersection of art and science provided a source of inspiration and wonder."

	if len(theme) == 0:
		theme = input("Please briefly describe what the resume is for. E.g., a research assistant position in Computer Science, a part-time in restaurant:")

	if len(content) == 0:
		content = input("Please paste the content of the resume:")

	reply_text = get_advice(theme, content)
	print(reply_text)
